# Generated by Django 4.2.4 on 2023-08-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='Beneficiary',
            new_name='beneficiary',
        ),
    ]
