# Generated by Django 4.2.4 on 2023-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_beneficiary_state_benficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabraa',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
