# Generated by Django 4.2.4 on 2023-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_tabraa_benefactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabraa',
            name='benefactor',
            field=models.ManyToManyField(null=True, to='project.benefactor'),
        ),
    ]
