# Generated by Django 4.2.4 on 2023-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_tabraa_benefactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
